CREATE TYPE "paymentmethods" AS ENUM (
	'CreditCard',
	'Cash',
	'CCE'
);

CREATE TYPE "transactionstatus" AS ENUM (
	'accepted',
	'canceled',
	'inProgress'
);

CREATE TYPE "paymentstatus" AS ENUM (
	'accepted',
	'canceled'
);

CREATE TYPE "pumpchargerstatus" AS ENUM (
	'inUse',
	'available',
	'deactivated',
	'outOfOrder'
);

CREATE TYPE "ccestatus" AS ENUM (
	'activated',
	'deactivated'
);

CREATE TYPE "restockstatus" AS ENUM (
	'pending',
	'delivered',
	'canceled'
);

CREATE TYPE "documentstatus" AS ENUM (
	'pending',
	'sentToDR',
	'locked'
);

CREATE TABLE IF NOT EXISTS "Transactions" (
	"idTransaction" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"type" VARCHAR(255) NOT NULL,
	"transactionDate" DATE,
	"isFromAutomat" BOOLEAN NOT NULL,
	"status" TRANSACTIONSTATUS NOT NULL,
	PRIMARY KEY("idTransaction")
);




CREATE TABLE IF NOT EXISTS "Products" (
	"idProduct" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"unitPrice" NUMERIC NOT NULL,
	"idShop" INTEGER NOT NULL,
	"stock" INTEGER NOT NULL,
	"alertThreshold" INTEGER NOT NULL,
	"idItem" INTEGER,
	PRIMARY KEY("idProduct")
);




CREATE TABLE IF NOT EXISTS "Fuels" (
	"idFuel" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pricePerLiter" NUMERIC NOT NULL,
	"stock" NUMERIC,
	"alertThreshold" NUMERIC NOT NULL,
	"idItem" INTEGER,
	PRIMARY KEY("idFuel")
);




CREATE TABLE IF NOT EXISTS "Pumps" (
	"idPump" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"volumeAvailable" NUMERIC NOT NULL,
	"isAutomat" BOOLEAN NOT NULL,
	"status" PUMPCHARGERSTATUS NOT NULL,
	PRIMARY KEY("idPump")
);




CREATE TABLE IF NOT EXISTS "EVChargers" (
	"idEVCharger" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"powerKW" INTEGER NOT NULL,
	"energyAvailable" NUMERIC NOT NULL,
	"alertThreshold" NUMERIC,
	"status" PUMPCHARGERSTATUS NOT NULL,
	PRIMARY KEY("idEVCharger")
);




CREATE TABLE IF NOT EXISTS "Clients" (
	"idClient" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"firstname" VARCHAR(255) NOT NULL,
	"lastname" VARCHAR(255) NOT NULL,
	"mail" VARCHAR(255) NOT NULL,
	"phoneNumber" VARCHAR(20) NOT NULL,
	"idCceCard" INTEGER NOT NULL,
	PRIMARY KEY("idClient")
);




CREATE TABLE IF NOT EXISTS "Users" (
	"idUser" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"role" VARCHAR(255) NOT NULL,
    "usesDarkMode" BOOLEAN NOT NULL,
    "tileLayout" JSONB NOT NULL,
	PRIMARY KEY("idUser")
);




CREATE TABLE IF NOT EXISTS "Shop" (
	"idShop" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"schedule" DATE NOT NULL,
	PRIMARY KEY("idShop")
);




CREATE TABLE IF NOT EXISTS "CceCards" (
	"idCceCard" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"balance" NUMERIC NOT NULL,
	"createdAt" DATE NOT NULL,
	"expiresAt" DATE NOT NULL,
	"code" INTEGER NOT NULL,
	"minimumCreditAmount" INTEGER NOT NULL,
	"status" CCESTATUS NOT NULL,
	PRIMARY KEY("idCceCard")
);




CREATE TABLE IF NOT EXISTS "Transactions_Lines" (
	"idTransactionLine" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	"idTransaction" INTEGER NOT NULL,
	"totalAmount" NUMERIC,
	"idItem" INTEGER NOT NULL,
	PRIMARY KEY("idTransactionLine")
);




CREATE TABLE IF NOT EXISTS "Pumps_Fuels" (
	"idPumpFuel" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"idFuel" INTEGER NOT NULL,
	"idPump" INTEGER NOT NULL,
	PRIMARY KEY("idPumpFuel")
);




CREATE TABLE IF NOT EXISTS "ManagementDocuments" (
	"idManagementDocument" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"lastModified" DATE,
	"content" TEXT,
	"status" DOCUMENTSTATUS NOT NULL,
	PRIMARY KEY("idManagementDocument")
);




CREATE TABLE IF NOT EXISTS "DailyTransactionsReports" (
	"idDailyTransactionReport" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"totalFuelVolume" DECIMAL NOT NULL,
	"totalElectricityVolume" DECIMAL NOT NULL,
	"totalProductVolume" DECIMAL NOT NULL,
	"transactionCount" INTEGER NOT NULL,
	"annexTransactionCount" INTEGER NOT NULL,
	"totalFuelsAmount" DECIMAL NOT NULL,
	"totalElectrecityAmount" DECIMAL NOT NULL,
	"totalProductsAmount" DECIMAL NOT NULL,
	"reportDate" DATE NOT NULL,
	"totalAmount" DECIMAL NOT NULL,
	"status" DOCUMENTSTATUS,
	PRIMARY KEY("idDailyTransactionReport")
);




CREATE TABLE IF NOT EXISTS "IncidentReports" (
	"idIncidentReport" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"type" VARCHAR(255),
	"date" DATE,
	"technicalDetail" VARCHAR(255),
	"resolution" VARCHAR(255),
	"status" DOCUMENTSTATUS NOT NULL,
	PRIMARY KEY("idIncidentReport")
);




CREATE TABLE IF NOT EXISTS "Transaction_Payments" (
	"idTransactionPayment" INTEGER NOT NULL,
	"idTransaction" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"paymentMethod" PAYMENTMETHODS NOT NULL,
	"amount" NUMERIC NOT NULL,
	"endNumCard" INTEGER,
	"status" TRANSACTIONSTATUS NOT NULL,
	"date" DATE NOT NULL,
	PRIMARY KEY("idTransactionPayment")
);




CREATE TABLE IF NOT EXISTS "Items" (
	"idItem" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"itemType" VARCHAR(255) NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("idItem")
);




CREATE TABLE IF NOT EXISTS "Restocks" (
	"idRestock" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"quantity" NUMERIC NOT NULL,
	"restockDate" DATE NOT NULL,
	"idItem" INTEGER NOT NULL,
	"status" RESTOCKSTATUS NOT NULL,
	PRIMARY KEY("idRestock")
);




CREATE TABLE IF NOT EXISTS "RegionalGuidelines" (
	"idRegionalGuideline" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"object" VARCHAR(255) NOT NULL,
	"content" VARCHAR(255) NOT NULL,
	PRIMARY KEY("idRegionalGuideline")
);



ALTER TABLE "Transactions_Lines"
ADD FOREIGN KEY("idTransaction") REFERENCES "Transactions"("idTransaction")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Products"
ADD FOREIGN KEY("idShop") REFERENCES "Shop"("idShop")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Clients"
ADD FOREIGN KEY("idCceCard") REFERENCES "CceCards"("idCceCard")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pumps_Fuels"
ADD FOREIGN KEY("idFuel") REFERENCES "Fuels"("idFuel")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Pumps_Fuels"
ADD FOREIGN KEY("idPump") REFERENCES "Pumps"("idPump")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Transaction_Payments"
ADD FOREIGN KEY("idTransaction") REFERENCES "Transactions"("idTransaction")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Transactions_Lines"
ADD FOREIGN KEY("idItem") REFERENCES "Items"("idItem")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Restocks"
ADD FOREIGN KEY("idItem") REFERENCES "Items"("idItem")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Products"
ADD FOREIGN KEY("idItem") REFERENCES "Items"("idItem")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Fuels"
ADD FOREIGN KEY("idItem") REFERENCES "Items"("idItem")
ON UPDATE NO ACTION ON DELETE NO ACTION;