spring.application.name=back

spring.datasource.url=jdbc:postgresql://localhost:5432/projet_4e
spring.datasource.username=4e_user
spring.datasource.password=4e_mdp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

jwt.secret=EZ8Zb3zNLRPl12zFXfsYx9r035xvk4wpcof8/q4SUObIQIghf2xX3LNg+2Vy0EM8+AoKJ7FfuXwabYbycgGJ7w==
jwt.expirationMs=86400000