-- Migration : ajout des séquences auto-incrément sur les clés primaires
-- À exécuter une seule fois sur la base existante (projet_4e).
-- Les valeurs START WITH sont calculées à partir des données existantes.

ALTER TABLE items              ALTER COLUMN id_item                  ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 16);
ALTER TABLE restocks           ALTER COLUMN id_restock               ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 7);
ALTER TABLE users              ALTER COLUMN id_user                  ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 4);
ALTER TABLE ev_chargers        ALTER COLUMN id_ev_charger            ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 11);
ALTER TABLE pumps              ALTER COLUMN id_pump                  ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 4);
ALTER TABLE pumps_fuels        ALTER COLUMN id_pump_fuel             ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 4);
ALTER TABLE cce_cards          ALTER COLUMN id_cce_card              ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 5);
ALTER TABLE clients            ALTER COLUMN id_client                ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 5);
ALTER TABLE transactions       ALTER COLUMN id_transaction           ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 148);
ALTER TABLE transactions_lines ALTER COLUMN id_transaction_line      ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 5);
ALTER TABLE transaction_payments ALTER COLUMN id_transaction_payment ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 4);
ALTER TABLE incident_reports   ALTER COLUMN id_incident_report       ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
ALTER TABLE regional_guidelines ALTER COLUMN id_regional_guideline   ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 3);
ALTER TABLE management_documents ALTER COLUMN id_management_document ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE daily_transactions_reports ALTER COLUMN id_daily_transaction_report ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE weekly_schedule    ALTER COLUMN id_weekly_schedule       ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
