package com.g1b.station_back.config;

public enum Permission {
	READ_CHARGERS, UPDATE_CHARGERS_STATUS,
	MANAGE_USERS,
	READ_ITEMS, CREATE_ITEMS, UPDATE_ITEMS, DELETE_ITEMS,
	READ_RESTOCKS, CREATE_RESTOCKS, UPDATE_RESTOCKS,
	MANAGE_CCE, UPDATE_CCE_SETTINGS, READ_CCE_SETTINGS,
	MANAGE_CUSTOMERS,
	MANAGE_INCIDENT_REPORT,
	MANAGE_MANAGEMENT_DOCUMENTS,
	MANAGE_DAILY_REPORTS,
	CREATE_PAYMENT,
	UPDATE_PUMPS,
	READ_TRANSACTIONS, CREATE_TRANSACTIONS, CANCEL_TRANSACTIONS
}
